# config.yaml
train_data_path:
  - 'data/BTCUSDT-3m-2023-06.csv'
  - 'data/BTCUSDT-3m-2023-07.csv'
  - 'data/BTCUSDT-3m-2023-08.csv'
  - 'data/BTCUSDT-3m-2023-09.csv'
  - 'data/BTCUSDT-3m-2023-10.csv'
  - 'data/BTCUSDT-3m-2023-11.csv'
val_data_path: 'data/BTCUSDT-3m-2023-12.csv'
test_data_path: 'data/BTCUSDT-3m-2024-01.csv'
download_dir: 'data'
device: 'mps'
data_limit: 1000000
target: 'Close'
seq_length: 60
batch_size: 4
hidden_dim: 64
num_layers: 3
learning_rate: 0.001
num_epochs: 15
dropout: 0.3