# config.yaml
train_data:
  - 'BTCUSDT-3m-2020-01.csv'
  - 'BTCUSDT-3m-2020-02.csv'
  - 'BTCUSDT-3m-2020-03.csv'
  - 'BTCUSDT-3m-2020-04.csv'
  - 'BTCUSDT-3m-2020-05.csv'
  - 'BTCUSDT-3m-2020-06.csv'
  - 'BTCUSDT-3m-2020-07.csv'
  - 'BTCUSDT-3m-2020-08.csv'
  - 'BTCUSDT-3m-2020-09.csv'
  - 'BTCUSDT-3m-2020-10.csv'
  - 'BTCUSDT-3m-2020-11.csv'
  - 'BTCUSDT-3m-2020-12.csv'
  - 'BTCUSDT-3m-2021-01.csv'
  - 'BTCUSDT-3m-2021-02.csv'
  - 'BTCUSDT-3m-2021-03.csv'
  - 'BTCUSDT-3m-2021-04.csv'
  - 'BTCUSDT-3m-2021-05.csv'
  - 'BTCUSDT-3m-2021-06.csv'
  - 'BTCUSDT-3m-2021-07.csv'
  - 'BTCUSDT-3m-2021-08.csv'
  - 'BTCUSDT-3m-2021-09.csv'
  - 'BTCUSDT-3m-2021-10.csv'
  - 'BTCUSDT-3m-2021-11.csv'
  - 'BTCUSDT-3m-2021-12.csv'
val_data:
  - 'BTCUSDT-3m-2022-01.csv'
  - 'BTCUSDT-3m-2022-02.csv'
  - 'BTCUSDT-3m-2022-03.csv'
  - 'BTCUSDT-3m-2022-04.csv'
  - 'BTCUSDT-3m-2022-05.csv'
  - 'BTCUSDT-3m-2022-06.csv'
  - 'BTCUSDT-3m-2022-07.csv'
  - 'BTCUSDT-3m-2022-08.csv'
  - 'BTCUSDT-3m-2022-09.csv'
  - 'BTCUSDT-3m-2022-10.csv'
  - 'BTCUSDT-3m-2022-11.csv'
  - 'BTCUSDT-3m-2022-12.csv'
test_data:
  - 'BTCUSDT-3m-2023-01.csv'
  - 'BTCUSDT-3m-2023-02.csv'
  - 'BTCUSDT-3m-2023-03.csv'
  - 'BTCUSDT-3m-2023-04.csv'
  - 'BTCUSDT-3m-2023-05.csv'
  - 'BTCUSDT-3m-2023-06.csv'
  - 'BTCUSDT-3m-2023-07.csv'
  - 'BTCUSDT-3m-2023-08.csv'
  - 'BTCUSDT-3m-2023-09.csv'
  - 'BTCUSDT-3m-2023-10.csv'
  - 'BTCUSDT-3m-2023-11.csv'
  - 'BTCUSDT-3m-2023-12.csv'
  - 'BTCUSDT-3m-2024-01.csv'
download_dir: 'data'
data_limit: 2000
target: 'Close'
seq_length: 60
batch_size: 4
hidden_dim: 64
num_layers: 3
learning_rate: 0.001
num_epochs: 15
dropout: 0.3
use_pca: True